services:
  - type: web
    name: swiftpos-api
    runtime: node
    rootDir: backend
    buildCommand: npm install --include=dev && npx prisma generate && npm run build
    startCommand: npx prisma migrate deploy && npm start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "10000"
      - key: API_PREFIX
        value: /api
      - key: APP_NAME
        value: SwiftPOS
      - key: DATABASE_URL
        sync: false
      - key: REDIS_URL
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_REFRESH_SECRET
        generateValue: true
      - key: JWT_EXPIRES_IN
        value: 15m
      - key: JWT_REFRESH_EXPIRES_IN
        value: 7d
      - key: BCRYPT_SALT_ROUNDS
        value: "12"
      - key: CORS_ORIGIN
        sync: false
      - key: RATE_LIMIT_WINDOW_MS
        value: "900000"
      - key: RATE_LIMIT_MAX
        value: "100"
      - key: UPLOAD_DIR
        value: uploads
      - key: MAX_FILE_SIZE
        value: "5242880"
      - key: LOG_LEVEL
        value: info
      - key: DEFAULT_CURRENCY
        value: KES
      - key: DEFAULT_TAX_RATE
        value: "16"
      - key: DEFAULT_TIMEZONE
        value: Africa/Nairobi
      - key: MPESA_CONSUMER_KEY
        sync: false
      - key: MPESA_CONSUMER_SECRET
        sync: false
      - key: MPESA_PASSKEY
        sync: false
      - key: MPESA_SHORTCODE
        value: "174379"
      - key: MPESA_ENV
        value: sandbox
      - key: MPESA_CALLBACK_URL
        sync: false


